name: Mirroring

on: [ push, delete ]

jobs:
  to_codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/attendance
          ssh_private_key:
            ${{ secrets.ATTENDANCE_SSH_KEY }}
          ssh_username:
            ${{ secrets.ATTENDANCE_SSH_KEY_ID }}
